ANDROID: selftest/mm: fix missing MAP_DROPPABLE definition
The MAP_DROPPABLE definition is missing from bionic header files, so add
a local temporary workaround while these get updated. This fixes the
following build issue:

  tools/testing/selftests/mm/mlock2-tests.c:360:22: error: use of undeclared identifier 'MAP_DROPPABLE'
    360 |                    MAP_ANONYMOUS | MAP_DROPPABLE, -1, 0);
        |                                    ^~~~~~~~~~~~~

Bug: 557760113
Fixes: c02dd57c57a6a ("selftests/mm: verify droppable mappings cannot be locked")
Change-Id: Ieb9ac8acfd8f3e73cfcb33623afb576f329ac69b
Signed-off-by: Carlos Llamas <cmllamas@google.com>
GitOrigin-RevId: 6b38b459a2223ba6486317bd9ae4ee399582d8cd